### PR TITLE
[WIP] PowerDNS pack - stub only

### PR DESCRIPTION
**Pull request by nzlosh**
This is only a stub without functional actions.  It was made for other community members to start adding functionality.

### CODE REVIEW

**Comment by LindsayHill** [comment]
@nzlosh you want me to create a new repo for this to create PRs against, or are you happy to leave it here while it's a stub?

**Comment by nzlosh** [comment]
I'm OK to leave it as a stub for now, a stub pack in the exchange will create frustration more than anything else I'd imagine.

The idea was to help a user in `#community` to bootstrap a pack for powerdns.  Unfortunately, the level of development knowledge required to code up the pack was too great.

I don't have time to work on the pack right now but will in the next month.

**Comment by nzlosh** [comment]
Can we move this to the exchange, I'm able to work on this now.

**Comment by nzlosh** [comment]
@armab Are you able to sort this out for me?

**Comment by armab** [comment]
Looks like there are some linting issues: https://circleci.com/gh/StackStorm-Exchange/exchange-incubator/40 that needs to be fixed before merging.

**Comment by armab** [comment]
Just added new integration pack `powerdns`:
https://github.com/StackStorm-Exchange/stackstorm-powerdns

Thanks again @nzlosh!

**Pull request closed without merging**
