### PR TITLE
nginxplus pack v1.0.0 - Initial Release / 2018-10-08

### PR DESCRIPTION
**Pull request by emptywee**
* Implemented all API endpoints documented at http://nginx.org/en/docs/http/ngx_http_api_module.html

### CODE REVIEW

**Comment by LindsayHill** [comment]
Looks good at first pass. Only question was about `http_runner` - does this pack rely on any of the other changes you were making? If so, we might need to specify a minimum stackstorm_version in pack.yaml

I've created a new repo at https://github.com/StackStorm-Exchange/stackstorm-nginxplus/ - can you do a PR against that?

**Comment by emptywee** [comment]
@LindsayHill yeah, you are right, it's contingent on https://github.com/StackStorm/st2/pull/4379 being merged and released (because currently it lacks of PATCH method in the enum). What version should I mention as `stackstorm_version` in the PR made against the repo you created? 2.10? 2.11? 3.0?

**Comment by LindsayHill** [comment]
Make it 2.10. _Most_ likely that next release will be 3.0, but there's a possibility of shipping 2.10 between 2.9 and 3.0.

**Comment by emptywee** [comment]
@LindsayHill Actually, I stand corrected. http-runner doesn't really limit us with what http method to use. The PR I meantioned above fixes the core.http action, which I am not using in the pack. So the pack can be used with any st2 release as long as there's http-runner available.

**Comment by emptywee** [comment]
I'll update the pack and remove the limitation.

**Comment by LindsayHill** [comment]
New pack published at 
https://github.com/StackStorm-Exchange/stackstorm-nginxplus/

**Pull request closed without merging**
