### PR TITLE
telegram integration pack

### PR DESCRIPTION
**Pull request by psychopenguin**
integration pack for telegram with send_message action and sensor to retrieve updates.

### CODE REVIEW

**Comment by LindsayHill** [comment]
Sorry that we somehow missed reviewing this. Question: Do you need to keep this under GPLv3? We normally license as Apache v2.

**Comment by psychopenguin** [comment]
We can change do Apache :)

**Comment by psychopenguin** [comment]
done!

**Comment by LindsayHill** [comment]
Thanks @psychopenguin - I've created a new repo for this, https://github.com/StackStorm-Exchange/stackstorm-telegram

Can you add an `icon.png` to the pack, and create a PR against the new repo? That should also trigger linting checks.

**Comment by LindsayHill** [comment]
Closed in favour of https://github.com/StackStorm-Exchange/stackstorm-telegram/issues/1

**Comment by psychopenguin** [comment]
@LindsayHill I see you already have done the job. Thanks for that, I really appreciate for that, as I'm quite busy for these days. ;)

**Comment by LindsayHill** [comment]
You did most of the work doing the initial pack, I just had a bit of
cleanup :)

**Pull request closed without merging**
