### PR TITLE
Added stackstorm pack for finding and formatting workflow errors

### PR DESCRIPTION
**Pull request by jschoewe**
Added stackstorm pack for finding and formatting workflow errors

### CODE REVIEW

**Comment by nmaludy** [comment]
@jschoewe is this good to go, i know Alex was still working on it at some point.

**Comment by jschoewe** [comment]
@nmaludy yes this is ready. Been using it at encore for a few weeks now with no issues

**Comment by nmaludy** [comment]
OK, i'll try and make a new repo here during lunch.

**Comment by nmaludy** [comment]
@jschoewe please make a PR against the new repo: https://github.com/StackStorm-Exchange/stackstorm-errors

**Pull request closed without merging**
