### PR TITLE
TheHive pack

### PR DESCRIPTION
**Pull request by agix**
Don't know if it will work by linking to the github repository with the wip thehive pack.

### CODE REVIEW

**Comment by blag** [comment]
I think you messed up [the submodules](https://circleci.com/gh/StackStorm-Exchange/exchange-incubator/55):

> fatal: No url found for submodule path 'thehive' in .gitmodules

Pack repo: https://github.com/agix/stackstorm-thehive
Python library: https://github.com/agix/TheHive4py
Website: https://thehive-project.org/
Description:

> A scalable, open source and free Security Incident Response Platform, tightly integrated with MISP (Malware Information Sharing Platform), designed to make life easier for SOCs, CSIRTs, CERTs and any information security practitioner dealing with security incidents that need to be investigated and acted upon swiftly.

**Comment by agix** [comment]
Wow you are quick to respond !

**Comment by punkrokk** [comment]
Excited to try out this pack. LMK if you need any help testing or anything

**Comment by m4dcoder** [comment]
@agix Sorry I'm unfamiliar w/ the internal process and had to revert the merge. Can you resubmit this PR? Thanks.

**Comment by agix** [comment]
Ok, anyway I'm working on another version with webhook instead of sensors,
and I have a lot of things to improve so I'll PR later.

**Comment by m4dcoder** [comment]
@agix You don't need to resubmit this specific PR.  We've transferred your pack to https://github.com/StackStorm-Exchange/stackstorm-thehive.  You can submit new version of your pack directly to StackStorm-Exchange/stackstorm-thehive.

**Comment by agix** [comment]
Ok, few more git tricks later I forked your stackstorm-exchange repo and
made my new PR.

Thank you for you trust.

**Pull request merged**
