### PR TITLE
Includes new stackstorm-aoscx pack

### PR DESCRIPTION
**Pull request by tchiapuziowong**
- New StackStorm integration with AOS-CX devices
- Includes workflows with third-party frameworks like Ansible

### CODE REVIEW

**Comment by tchiapuziowong** [comment]
Pyaoscx updated : https://pypi.org/project/pyaoscx/
https://github.com/aruba/pyaoscx/pull/1

**Comment by tchiapuziowong** [comment]
Hello! Is there any way to re-launch this test?

**Comment by punkrokk** [comment]
You can also do a commit. Restarted

JP Bourget / @punkrokk

**Comment by tchiapuziowong** [comment]
Hello! Is there any update to this?

**Comment by amanda11** [comment]
I took a look at the failure, and re-ran build. But I wonder if the problem is that the library is python 3 only. As the build failure shows:
`Using /home/circleci/virtualenv/lib/python2.7/site-packages
Finished processing dependencies for st2common==3.3.dev0
Installing pack requirements from /home/circleci/repo/requirements.txt
Requirement already satisfied: requests in /home/circleci/virtualenv/lib/python2.7/site-packages (from -r /home/circleci/repo/requirements.txt (line 1))
Collecting tornado (from -r /home/circleci/repo/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz (516kB)
    100% |████████████████████████████████| 522kB 1.6MB/s eta 0:00:01
Collecting pyaoscx>=0.2.1 (from -r /home/circleci/repo/requirements.txt (line 3))
  Could not find a version that satisfies the requirement pyaoscx>=0.2.1 (from -r /home/circleci/repo/requirements.txt (line 3)) (from versions: 0.1.1, 0.1.2, 0.2.0)
`
But python_versions is listed as 3 only, so I'm not sure why its trying to run in  a python 2.7 enviornment.
So it looks like it is trying to run in python 2 environment.

**Comment by tchiapuziowong** [comment]
Hi @amanda11 ! Thank you so much for looking into this! It appears this review cannot pass CircleCi unless https://github.com/StackStorm-Exchange/exchange-incubator/pull/155 is merged. I'll ask for an update on that review as well. Thank you again for your support!

**Comment by blag** [comment]
You also need to add a `LICENSE` file with the Apache license text (packs listed on StackStorm-Exchange MUST be licensed under the Apache 2 license).

See the `LICENSE` file in the stackstorm-vault pack: https://github.com/StackStorm-Exchange/stackstorm-vault/blob/master/LICENSE

**Comment by blag** [comment]
The pylint linter is having trouble ensuring that `aoscx_websocket` is an importable package:
```
************* Module port_sensor
E:  2, 0: Unable to import 'aoscx_websocket' (import-error)
```

Import line is [here](https://github.com/StackStorm-Exchange/exchange-incubator/pull/154/files#diff-925943dec4fd37a615022e624188643057007fdb1600e946646563a24140135cR2):

```python
from aoscx_websocket import Client  # NOQA
```

Is that package open source and available on PyPI?

**Comment by tchiapuziowong** [comment]
Hello - is there any update to this? @blag

**Comment by nmaludy** [comment]
Closing this PR since https://github.com/StackStorm-Exchange/stackstorm-aoscx was created with your code. Enjoy!

**Pull request closed without merging**
