### PR TITLE
GitLab Integration Pack

### PR DESCRIPTION
**Pull request by nullkarma**

### CODE REVIEW

**Comment by nullkarma** [comment]
I removed the workflow that has a dependency on the tools pack.

**Comment by LindsayHill** [comment]
I've created a new repo for this, github.com/StackStorm-Exchange/stackstorm-gitlab

Can you create a PR against that? That will trigger linting checks.

Also, please:
- add an icon.png
- rename `gitlab.example.yaml` to `gitlab.yaml.example` - this will make sure that the config schema gets validated against the example config, as part of CI checks

**Comment by nullkarma** [comment]
I'll create the PR

**Comment by LindsayHill** [comment]
Transferred here https://github.com/StackStorm-Exchange/stackstorm-gitlab/pull/1

**Pull request closed without merging**
