### PR TITLE
Initial pack creation.

### PR DESCRIPTION
**Pull request by nzlosh**
I'd like to submit a new pack that can be used to log message to syslog servers and also doubles a action logger via StackStorm's notification triggers.

### CODE REVIEW

**Comment by LindsayHill** [comment]
Y'know, we're probably going to end up needing to add a syslog sensor to this pack. Maybe we should integrate ghost2logger? https://github.com/StackStorm-Exchange/stackstorm-ghost2logger

I'll create a new repo in the next day or so, and transfer this over.

**Comment by nzlosh** [comment]
Coming from a large scale architecture, we already have centralised log management system in place that's able to ingest, process, enrich and output logs in a format compatible with StackStorm's generic web hooks which makes ghost2logger redundant in our case.  I'd expect other medium/large scale environments would be in a similar situation. 

I think it would be more flexible to keep the syslog (client) separate from the ghost2logger pack (server) since they provide complementary features but don't have hard dependencies on each other nor share a common code base.  They aren't mutually exclusive so any smaller scale setups that don't already have central logging with syslog-ng/logstash/fleuntd/etc can install ghost2logger for their log2st2trigger processing needs.

**Comment by LindsayHill** [comment]
I fully agreee that using a proper log management system (Splunk/Elastic/etc) is the correct way to go. 

But there's a surprising number of people who have *no* log management systems installed, and they will see the "syslog" pack, and assume that it acts as a syslog server. That will then lead to many support questions. 

That's why I wonder if we should combine with ghost2logger, or tweak the name of this pack, e.g. syslog-client?

**Comment by nzlosh** [comment]
I agree with what you're saying.  How about we change the name to syslog-client and add a big notice in the readme saying that if the user needs to ingest and process logging a syslog-server sensor can be obtained by installing ghost2logger <link etc>?

**Comment by LindsayHill** [comment]
Yep, that sounds like a good idea. Just want to reduce potential confusion & support questions.

**Comment by LindsayHill** [comment]
New repo: https://github.com/StackStorm-Exchange/stackstorm-syslog_client

**Pull request closed without merging**
